# Generated by Django 3.1.5 on 2024-07-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20240709_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_section',
            field=models.ManyToManyField(blank=True, to='courses.CourseSection'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='episode',
            field=models.ManyToManyField(blank=True, to='courses.Episode'),
        ),
    ]
