# Generated by Django 3.1.5 on 2024-07-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20240709_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='related_courses',
            new_name='related_course',
        ),
    ]
